# Generated by Django 2.2.7 on 2020-03-20 18:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_name', models.CharField(max_length=200)),
                ('bus_start', models.CharField(max_length=200)),
                ('bus_end_stop', models.CharField(max_length=200)),
                ('bus_start_time', models.TimeField()),
                ('bus_all_seet', models.IntegerField()),
                ('bus_status', models.CharField(choices=[('1', 'active'), ('0', 'deactive')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OnerSignup',
            fields=[
                ('oner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='media')),
                ('contact', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserSingup',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('user_image', models.ImageField(upload_to='media')),
                ('user_address', models.CharField(max_length=200)),
                ('user_city', models.CharField(max_length=200)),
                ('user_state', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_contact', models.IntegerField()),
                ('user_status', models.CharField(choices=[('1', 'active'), ('0', 'deactive')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BusBooking',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(choices=[('0', 'Free'), ('1', 'Booked')], max_length=20)),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstm.Bus')),
                ('user_book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstm.UserSingup')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_oner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstm.OnerSignup'),
        ),
    ]
