# Generated by Django 2.2.7 on 2020-03-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onersignup',
            name='password',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersingup',
            name='password',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
